In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/preproc_coins.csv')
len(df)

736065

In [3]:
df.sample(5)

,time_idx,symbol,open_log,high_log,low_log,close_log,volume_log,btc_close_log,eth_close_log,eth_btc_ratio,hour_sin,hour_cos,norm_day_sin,norm_day_cos,weekday_sin,weekday_cos,month_sin,month_cos,year,next_close_log
164424,11218,BCH/USD,0.004266,0.003467,0.003129,0.001291,15.495155,0.012012,0.007259,0.032351,-0.866025,-5.000000e-01,0.897805,-0.440394,0.974928,-0.222521,1.000000,6.123234e-17,1.1,0.022852
481868,15470,LTC/USD,-0.007151,-0.003743,-0.006485,-0.011902,14.579618,-0.000699,-0.006914,0.020812,-1.000000,-1.836970e-16,-0.587785,-0.809017,0.974928,-0.222521,-1.000000,-1.836970e-16,0.9,0.002544
460412,35677,LINK/USD,-0.005323,-0.006457,-0.001592,0.000289,13.647001,-0.000187,0.000446,0.069956,-0.258819,-9.659258e-01,0.433884,-0.900969,-0.781831,0.623490,0.866025,5.000000e-01,1.3,0.004461
187261,34055,BCH/USD,0.000873,-0.000870,-0.007898,-0.008317,13.582112,-0.000677,-0.001127,0.055393,-0.965926,-2.588190e-01,-0.485302,-0.874347,0.974928,-0.222521,-0.866025,5.000000e-01,1.3,0.000879
470156,3758,LTC/USD,-0.002037,0.014458,-0.001136,0.018261,12.904966,0.012147,0.011132,0.083720,-1.000000,-1.836970e-16,-0.485302,-0.874347,-0.433884,-0.900969,0.500000,-8.660254e-01,0.8,0.013846

In [4]:
df['symbol'].unique()  # 19 total

array(['ADA/USD', 'ALGO/USD', 'ATOM/USD', 'BAL/USD', 'BCH/USD', 'BNB/USD',
       'COMP/USD', 'DENT/USD', 'DOGE/USD', 'ETC/USD', 'HBAR/USD',
       'LINK/USD', 'LTC/USD', 'MATIC/USD', 'MKR/USD', 'RVN/USD',
       'SOL/USD', 'TRX/USD', 'XMR/USD'], dtype=object)

In [5]:
df['eth_btc_ratio'].describe()

count    736065.000000
mean          0.051841
std           0.021018
min           0.016210
25%           0.031000
50%           0.061544
75%           0.069838
max           0.122217
Name: eth_btc_ratio, dtype: float64

In [6]:
df['symbol'].value_counts()

symbol
BNB/USD      52030
LTC/USD      51283
ADA/USD      48196
ETC/USD      46940
TRX/USD      46903
LINK/USD     41663
XMR/USD      40314
MATIC/USD    39241
ATOM/USD     39180
ALGO/USD     37898
DOGE/USD     37574
DENT/USD     36318
RVN/USD      35614
HBAR/USD     35526
BCH/USD      34084
COMP/USD     29057
MKR/USD      28380
BAL/USD      27932
SOL/USD      27932
Name: count, dtype: int64

In [7]:
variance = df.groupby('symbol')['close_log'].var().reset_index()
variance.rename(columns={'close_log':'var'}, inplace= True)
variance = variance.sort_values(by='var', ascending=False)

In [8]:
variance

       symbol       var
13  MATIC/USD  0.000276
7    DENT/USD  0.000263
16    SOL/USD  0.000234
10   HBAR/USD  0.000214
8    DOGE/USD  0.000214
1    ALGO/USD  0.000200
15    RVN/USD  0.000197
6    COMP/USD  0.000192
2    ATOM/USD  0.000184
11   LINK/USD  0.000174
3     BAL/USD  0.000156
14    MKR/USD  0.000154
9     ETC/USD  0.000148
5     BNB/USD  0.000144
0     ADA/USD  0.000134
12    LTC/USD  0.000133
4     BCH/USD  0.000120
17    TRX/USD  0.000113
18    XMR/USD  0.000104

In [9]:
rg = pd.read_csv('../data/coins.csv')

In [10]:
rg.groupby('symbol')['date'].min()

symbol
ADA/USD      2018-04-17 04:00:00
ALGO/USD     2019-06-22 00:00:00
ATOM/USD     2019-04-29 04:00:00
BAL/USD      2020-08-11 06:00:00
BCH/USD      2019-11-28 10:00:00
BNB/USD      2017-11-06 03:00:00
BTC/USD      2017-08-17 04:00:00
COMP/USD     2020-06-25 06:00:00
DENT/USD     2019-08-27 04:00:00
DOGE/USD     2019-07-05 12:00:00
ETC/USD      2018-06-12 02:00:00
ETH/USD      2017-08-17 04:00:00
HBAR/USD     2019-09-29 04:00:00
LINK/USD     2019-01-16 10:00:00
LTC/USD      2017-12-13 03:00:00
MATIC/USD    2019-04-26 15:00:00
MKR/USD      2020-07-23 14:00:00
RVN/USD      2019-09-25 12:00:00
SOL/USD      2020-08-11 06:00:00
TRX/USD      2018-06-11 11:00:00
XMR/USD      2019-03-15 04:00:00
Name: date, dtype: object