In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../data/preprocessed/crypto_data_proc.csv')
len(df)

1011769

In [4]:
df.sample(5) #.to_csv('./random_sample.csv', index= True)

,time_idx,token,open_log,high_log,low_log,close_log,volume_log,btc_close_log,eth_close_log,eth_btc_ratio,hour_sin,hour_cos,norm_day_sin,norm_day_cos,weekday_sin,weekday_cos,month_sin,month_cos,year,next_close_log
52220,1179,ADA,-0.004457,0.019710,0.001658,0.014749,14.455917,0.005980,0.012894,0.079664,0.866025,-0.500000,0.866025,0.500000,0.781831,0.623490,1.224647e-16,-1.000000e+00,2018,-0.008071
793322,8237,RVN,-0.005817,-0.004845,-0.017656,-0.017622,10.658741,-0.007445,-0.014331,0.037721,0.500000,-0.866025,0.587785,0.809017,0.433884,-0.900969,-1.000000e+00,-1.836970e-16,2020,-0.014926
835410,14711,SHIB,-0.008273,0.000000,0.000000,0.000000,14.691528,0.006391,0.003853,0.073593,-0.965926,-0.258819,0.485302,-0.874347,-0.433884,-0.900969,5.000000e-01,8.660254e-01,2023,-0.005206
922076,24591,TRX,-0.006951,0.019004,0.010075,0.019606,16.295796,-0.001889,-0.006929,0.035605,0.965926,-0.258819,0.587785,0.809017,-0.974928,-0.222521,8.660254e-01,-5.000000e-01,2021,0.001653
147965,10830,ATOM,-0.002808,-0.003567,-0.006682,-0.001538,12.778675,-0.002472,-0.003295,0.029692,-0.707107,0.707107,-0.988468,0.151428,-0.433884,-0.900969,-5.000000e-01,-8.660254e-01,2020,-0.014991

In [5]:
df['token'].unique()  # 30 total

array(['1INCH', 'AAVE', 'ADA', 'ALGO', 'ATOM', 'AVAX', 'BAL', 'BCH',
       'BNB', 'COMP', 'CRV', 'DENT', 'DOGE', 'DOT', 'DYDX', 'ETC', 'FIL',
       'HBAR', 'ICP', 'LINK', 'LTC', 'MATIC', 'MKR', 'RVN', 'SHIB', 'SOL',
       'SUSHI', 'TRX', 'UNI', 'XMR'], dtype=object)

In [6]:
df['eth_btc_ratio'].describe()

count    1.011769e+06
mean     5.497387e-02
std      2.002850e-02
min      1.620956e-02
25%      3.294340e-02
50%      6.341496e-02
75%      7.056102e-02
max      1.222169e-01
Name: eth_btc_ratio, dtype: float64

In [7]:
df['token'].value_counts()

token
BNB      52030
LTC      51283
ADA      48196
ETC      46940
TRX      46903
LINK     41663
XMR      40314
MATIC    39241
ATOM     39180
ALGO     37898
DOGE     37574
DENT     36318
RVN      35614
HBAR     35526
BCH      34084
COMP     29057
MKR      28380
BAL      27932
SOL      27932
CRV      27838
DOT      27747
SUSHI    27443
UNI      27067
AVAX     26924
AAVE     26371
FIL      26361
1INCH    24670
SHIB     21411
ICP      21397
DYDX     18475
Name: count, dtype: int64

In [8]:
variance = df.groupby('token')['close_log'].var().reset_index()
variance.rename(columns={'close_log':'var'}, inplace= True)
variance = variance.sort_values(by='var', ascending=False)

In [9]:
variance

    token       var
26  SUSHI  0.000309
10    CRV  0.000306
21  MATIC  0.000276
11   DENT  0.000263
25    SOL  0.000234
5    AVAX  0.000229
14   DYDX  0.000215
17   HBAR  0.000214
12   DOGE  0.000214
24   SHIB  0.000207
0   1INCH  0.000203
18    ICP  0.000200
3    ALGO  0.000200
28    UNI  0.000199
23    RVN  0.000197
1    AAVE  0.000193
9    COMP  0.000192
4    ATOM  0.000184
19   LINK  0.000174
16    FIL  0.000169
13    DOT  0.000160
6     BAL  0.000156
22    MKR  0.000154
15    ETC  0.000148
8     BNB  0.000144
2     ADA  0.000134
20    LTC  0.000133
7     BCH  0.000120
27    TRX  0.000113
29    XMR  0.000104

In [10]:
rg = pd.read_csv('../data/raw/aggregated/crypto_data.csv')

In [12]:
rg.groupby('token')['date'].min()

token
1INCH    2020-12-25 05:00:00
AAVE     2020-10-15 03:00:00
ADA      2018-04-17 04:00:00
ALGO     2019-06-22 00:00:00
ATOM     2019-04-29 04:00:00
AVAX     2020-09-22 06:00:00
BAL      2020-08-11 06:00:00
BCH      2019-11-28 10:00:00
BNB      2017-11-06 03:00:00
BTC      2017-08-17 04:00:00
COMP     2020-06-25 06:00:00
CRV      2020-08-15 04:00:00
DENT     2019-08-27 04:00:00
DOGE     2019-07-05 12:00:00
DOT      2020-08-18 23:00:00
DYDX     2021-09-09 02:00:00
ETC      2018-06-12 02:00:00
ETH      2017-08-17 04:00:00
FIL      2020-10-15 17:00:00
HBAR     2019-09-29 04:00:00
ICP      2021-05-11 01:00:00
LINK     2019-01-16 10:00:00
LTC      2017-12-13 03:00:00
MATIC    2019-04-26 15:00:00
MKR      2020-07-23 14:00:00
RVN      2019-09-25 12:00:00
SHIB     2021-05-10 11:00:00
SOL      2020-08-11 06:00:00
SUSHI    2020-09-01 11:00:00
TRX      2018-06-11 11:00:00
UNI      2020-09-17 03:00:00
XMR      2019-03-15 04:00:00
Name: date, dtype: object