In [46]:
import pandas as pd

In [47]:
df = pd.read_csv('../data/crypto_data.csv')

In [48]:
df.head()

,date,symbol,open,high,low,close,volume usdt,tradecount,token,hour,weekday
0,2020-12-25 05:00:00,1INCHUSDT,0.2000,3.0885,0.2000,2.5826,35530516,48768,1INCH,5,Friday
1,2020-12-25 06:00:00,1INCHUSDT,2.5824,2.6900,2.2249,2.5059,22440875,31099,1INCH,6,Friday
2,2020-12-25 07:00:00,1INCHUSDT,2.5152,2.8870,2.3609,2.6237,21300426,33001,1INCH,7,Friday
3,2020-12-25 08:00:00,1INCHUSDT,2.6318,2.8247,2.4650,2.6134,17491813,30459,1INCH,8,Friday
4,2020-12-25 09:00:00,1INCHUSDT,2.6104,2.7498,2.5629,2.6365,9919400,21023,1INCH,9,Friday

In [49]:
print(df['date'].min())
print(df['date'].max())

2017-08-17 04:00:00
2023-10-19 23:00:00

Drop stupid columns

In [50]:
df.drop(columns=['symbol', 'tradecount'], inplace=True)
df.head()

,date,open,high,low,close,volume usdt,token,hour,weekday
0,2020-12-25 05:00:00,0.2000,3.0885,0.2000,2.5826,35530516,1INCH,5,Friday
1,2020-12-25 06:00:00,2.5824,2.6900,2.2249,2.5059,22440875,1INCH,6,Friday
2,2020-12-25 07:00:00,2.5152,2.8870,2.3609,2.6237,21300426,1INCH,7,Friday
3,2020-12-25 08:00:00,2.6318,2.8247,2.4650,2.6134,17491813,1INCH,8,Friday
4,2020-12-25 09:00:00,2.6104,2.7498,2.5629,2.6365,9919400,1INCH,9,Friday

In [51]:
df['date'] = pd.to_datetime(df['date'])
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day

In [52]:
c = df.columns
df['time_idx'] = df.groupby('token').cumcount()
df = df.reindex(columns=['time_idx', *c])

df['volume_usdt'] = df['volume usdt']
df.drop(columns=['volume usdt'])

,time_idx,date,open,high,low,close,token,hour,weekday,year,month,day,volume_usdt
0,0,2020-12-25 05:00:00,0.2000,3.0885,0.2000,2.5826,1INCH,5,Friday,2020,12,25,35530516
1,1,2020-12-25 06:00:00,2.5824,2.6900,2.2249,2.5059,1INCH,6,Friday,2020,12,25,22440875
2,2,2020-12-25 07:00:00,2.5152,2.8870,2.3609,2.6237,1INCH,7,Friday,2020,12,25,21300426
3,3,2020-12-25 08:00:00,2.6318,2.8247,2.4650,2.6134,1INCH,8,Friday,2020,12,25,17491813
4,4,2020-12-25 09:00:00,2.6104,2.7498,2.5629,2.6365,1INCH,9,Friday,2020,12,25,9919400
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1120056,40311,2023-10-19 19:00:00,151.0000,152.1000,151.0000,152.0000,XMR,19,Thursday,2023,10,19,220241
1120057,40312,2023-10-19 20:00:00,152.0000,152.3000,151.5000,151.6000,XMR,20,Thursday,2023,10,19,226736
1120058,40313,2023-10-19 21:00:00,151.7000,152.4000,151.4000,151.9000,XMR,21,Thursday,2023,10,19,373900
1120059,40314,2023-10-19 22:00:00,151.8000,152.0000,151.3000,151.7000,XMR,22,Thursday,2023,10,19,156049
1120060,40315,2023-10-19 23:00:00,151.7000,152.6000,151.7000,152.5000,XMR,23,Thursday,2023,10,19,411510

In [53]:
df.sample(20)

,time_idx,date,open,high,low,close,volume usdt,token,hour,weekday,year,month,day,volume_usdt
595081,46641,2023-10-07 11:00:00,15.660000,15.700000,15.610000,15.640000,80458,ETC,11,Saturday,2023,10,7,80458
783032,8579,2018-12-05 14:00:00,30.710000,30.740000,29.960000,30.190000,226481,LTC,14,Wednesday,2018,12,5,226481
793205,18752,2020-02-02 11:00:00,71.320000,71.770000,71.010000,71.740000,2211455,LTC,11,Sunday,2020,2,2,2211455
9020,9020,2022-01-05 14:00:00,2.557000,2.570000,2.536000,2.561000,1314885,1INCH,14,Wednesday,2022,1,5,1314885
721559,10170,2022-07-09 01:00:00,6.980000,7.000000,6.900000,6.910000,708395,ICP,1,Saturday,2022,7,9,708395
695011,19150,2021-12-06 12:00:00,0.252400,0.256700,0.249800,0.252000,733654,HBAR,12,Monday,2021,12,6,733654
942006,13027,2022-11-04 12:00:00,0.000012,0.000013,0.000012,0.000013,6215610,SHIB,12,Friday,2022,11,4,6215610
609874,14492,2019-04-13 00:00:00,163.200000,163.800000,162.630000,163.040000,714783,ETH,0,Saturday,2019,4,13,714783
825278,50825,2023-09-30 20:00:00,66.310000,66.410000,66.200000,66.400000,513089,LTC,20,Saturday,2023,9,30,513089
391464,20045,2022-10-09 08:00:00,59.140000,59.400000,58.990000,59.180000,66707,COMP,8,Sunday,2022,10,9,66707
14947,14947,2022-09-09 13:00:00,0.670000,0.670000,0.661000,0.664000,217992,1INCH,13,Friday,2022,9,9,217992
891830,26849,2023-08-17 02:00:00,1133.000000,1138.000000,1129.000000,1137.000000,99942,MKR,2,Thursday,2023,8,17,99942
283767,18496,2019-12-22 07:00:00,13.366000,13.470200,13.334700,13.470200,1032269,BNB,7,Sunday,2019,12,22,1032269
191726,15401,2022-06-26 17:00:00,20.810000,20.900000,20.320000,20.450000,3351802,AVAX,17,Sunday,2022,6,26,3351802
811450,36997,2022-03-03 16:00:00,110.000000,111.200000,108.600000,109.800000,8932850,LTC,16,Thursday,2022,3,3,8932850
462795,34477,2023-08-04 04:00:00,0.000754,0.000755,0.000750,0.000755,15367,DENT,4,Friday,2023,8,4,15367
606495,11113,2018-11-23 05:00:00,124.940000,126.730000,122.710000,126.000000,3833750,ETH,5,Friday,2018,11,23,3833750
889333,24352,2023-05-05 01:00:00,688.000000,696.000000,687.000000,693.000000,250814,MKR,1,Friday,2023,5,5,250814
149220,12077,2020-09-14 19:00:00,5.383000,5.416000,5.351000,5.388000,137822,ATOM,19,Monday,2020,9,14,137822
577174,28734,2021-09-21 08:00:00,49.830000,50.230000,49.590000,50.050000,2953324,ETC,8,Tuesday,2021,9,21,2953324

In [ ]:
df['volume_usdt'].describe()

count    1.120061e+06
mean     7.666081e+06
std      3.244000e+07
min      0.000000e+00
25%      1.944980e+05
50%      8.186540e+05
75%      3.267840e+06
max      3.005634e+09
Name: volume_usdt, dtype: float64