In [57]:
import pandas as pd
import numpy as np

In [66]:
df = pd.read_csv('../data/raw/aggregated/crypto_data.csv')
df.sample(5)

,date,open,high,low,close,volume,token
677238,2019-11-25 17:00:00,0.02464,0.02477,0.0246,0.02477,587,HBAR
382950,2021-10-19 14:00:00,304.40000,305.70000,301.0000,304.60000,912040,COMP
790753,2019-10-23 07:00:00,52.46000,52.52000,52.2800,52.30000,323463,LTC
509561,2021-06-21 14:00:00,18.23400,18.24300,17.5190,17.87400,18465399,DOT
869495,2021-01-27 21:00:00,1388.99000,1390.88000,1352.1800,1358.79000,286846,MKR

## Extraction

In [60]:
# For feature engineering; we do not intend to trade these 
# symbols because the market is too efficient.
btc = df[df['token'] == 'BTC']
eth = df[df['token'] == 'ETH']
btc.head()

                       date     open     high      low    close  volume token
317303  2017-08-17 04:00:00  4261.48  4313.62  4261.32  4308.83  202366   BTC
317304  2017-08-17 05:00:00  4308.83  4328.69  4291.37  4315.32  100305   BTC
317305  2017-08-17 06:00:00  4330.29  4345.45  4309.37  4324.35   31282   BTC
317306  2017-08-17 07:00:00  4316.62  4349.99  4287.41  4349.99   19241   BTC
317307  2017-08-17 08:00:00  4333.32  4377.85  4333.32  4360.69    4240   BTC

In [61]:
print(len(df['token'].unique()))
df = df[~df['token'].isin({'ETH', 'BTC'})]
print(len(df['token'].unique()))

32
30

## Feature engineering

In [62]:
# Create the target feature
df['next_close'] = df.groupby('token')['close'].shift(-1)
df.head()

,date,open,high,low,close,volume,token,next_close
0,2020-12-25 05:00:00,0.2000,3.0885,0.2000,2.5826,35530516,1INCH,2.5059
1,2020-12-25 06:00:00,2.5824,2.6900,2.2249,2.5059,22440875,1INCH,2.6237
2,2020-12-25 07:00:00,2.5152,2.8870,2.3609,2.6237,21300426,1INCH,2.6134
3,2020-12-25 08:00:00,2.6318,2.8247,2.4650,2.6134,17491813,1INCH,2.6365
4,2020-12-25 09:00:00,2.6104,2.7498,2.5629,2.6365,9919400,1INCH,2.7667

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1011829 entries, 0 to 1120060
Data columns (total 8 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   date        1011829 non-null  object
 1   open        1011829 non-null  float64
 2   high        1011829 non-null  float64
 3   low         1011829 non-null  float64
 4   close       1011829 non-null  float64
 5   volume      1011829 non-null  int64
 6   token       1011829 non-null  object
 7   next_close  1011799 non-null  float64
dtypes: float64(5), int64(1), object(2)
memory usage: 69.5+ MB