In [57]:
import pandas as pd
import numpy as np

In [58]:
df = pd.read_csv('../data/raw/aggregated/crypto_data.csv')
df.sample(5)

,date,symbol,open,high,low,close,volume usdt,tradecount,token,hour,day
719975,2022-05-04 01:00:00,ICPUSDT,13.060000,13.160000,13.010000,13.020000,611263,1750,ICP,1,Wednesday
312856,2023-04-17 17:00:00,BNBUSDT,339.900000,340.600000,339.600000,340.300000,3220092,7945,BNB,17,Monday
532262,2021-12-13 23:00:00,DYDXUSDT,8.093000,8.164000,7.997000,8.130000,1240121,3240,DYDX,23,Monday
428838,2019-09-17 20:00:00,DENTUSDT,0.000465,0.000469,0.000463,0.000469,4616,65,DENT,20,Tuesday
963659,2022-02-15 19:00:00,SOLUSDT,102.320000,102.440000,101.410000,101.600000,6401496,10563,SOL,19,Tuesday

## Structuring

In [59]:
df.drop(columns=['symbol', 'tradecount', 'day', 'hour'], inplace=True)
df.rename(columns={'volume usdt': 'volume'}, inplace=True)
df.sample(5)

,date,open,high,low,close,volume,token
655050,2021-06-04 13:00:00,88.490000,89.950000,87.620000,88.630000,16593646,FIL
454146,2022-08-08 18:00:00,0.001212,0.001212,0.001201,0.001206,59417,DENT
555195,2019-03-20 13:00:00,4.555700,4.558300,4.542700,4.546600,40310,ETC
971626,2023-01-13 18:00:00,16.900000,16.950000,16.720000,16.750000,3237901,SOL
204422,2020-09-29 01:00:00,15.351000,15.402000,15.047000,15.121000,106344,BAL

In [60]:
# For feature engineering; we do not intend to trade these 
# symbols because the market is too efficient.
btc = df[df['token'] == 'BTC']
eth = df[df['token'] == 'ETH']
btc.head()

                       date     open     high      low    close  volume token
317303  2017-08-17 04:00:00  4261.48  4313.62  4261.32  4308.83  202366   BTC
317304  2017-08-17 05:00:00  4308.83  4328.69  4291.37  4315.32  100305   BTC
317305  2017-08-17 06:00:00  4330.29  4345.45  4309.37  4324.35   31282   BTC
317306  2017-08-17 07:00:00  4316.62  4349.99  4287.41  4349.99   19241   BTC
317307  2017-08-17 08:00:00  4333.32  4377.85  4333.32  4360.69    4240   BTC

In [61]:
print(len(df['token'].unique()))
df = df[~df['token'].isin({'ETH', 'BTC'})]
print(len(df['token'].unique()))

32
30

## Feature engineering

In [62]:
# Create the target feature
df['next_close'] = df.groupby('token')['close'].shift(-1)
df.head()

,date,open,high,low,close,volume,token,next_close
0,2020-12-25 05:00:00,0.2000,3.0885,0.2000,2.5826,35530516,1INCH,2.5059
1,2020-12-25 06:00:00,2.5824,2.6900,2.2249,2.5059,22440875,1INCH,2.6237
2,2020-12-25 07:00:00,2.5152,2.8870,2.3609,2.6237,21300426,1INCH,2.6134
3,2020-12-25 08:00:00,2.6318,2.8247,2.4650,2.6134,17491813,1INCH,2.6365
4,2020-12-25 09:00:00,2.6104,2.7498,2.5629,2.6365,9919400,1INCH,2.7667

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1011829 entries, 0 to 1120060
Data columns (total 8 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   date        1011829 non-null  object
 1   open        1011829 non-null  float64
 2   high        1011829 non-null  float64
 3   low         1011829 non-null  float64
 4   close       1011829 non-null  float64
 5   volume      1011829 non-null  int64
 6   token       1011829 non-null  object
 7   next_close  1011799 non-null  float64
dtypes: float64(5), int64(1), object(2)
memory usage: 69.5+ MB